# -*- coding: utf-8 -*-
# Deployment settings for AmazingMaze.
# This file is autogenerated by the mkb system and used by the s3e deployment
# tool during the build process.

config = {}
cmdline = ['C:/Marmalade/7.5/s3e/makefile_builder/mkb.py', 'd:/School/cs115/AmazingMaze/AmazingMaze.mkb', '--buildenv=VC12', '--fake-vc-call', '--default-buildenv=vc12', '--msvc-project', '--deploy-only']
mkb = 'd:/School/cs115/AmazingMaze/AmazingMaze.mkb'
mkf = ['c:\\marmalade\\7.5\\s3e\\s3e-default.mkf', 'c:\\marmalade\\7.5\\modules\\iwutil\\iwutil.mkf', 'c:\\marmalade\\7.5\\modules\\third_party\\libjpeg\\libjpeg.mkf', 'c:\\marmalade\\7.5\\modules\\third_party\\libpng\\libpng.mkf', 'c:\\marmalade\\7.5\\modules\\third_party\\zlib\\zlib.mkf', 'c:\\marmalade\\7.5\\modules\\iw2dscenegraphcore\\iw2dscenegraphcore.mkf', 'c:\\marmalade\\7.5\\modules\\iw2dscenegraph\\iw2dscenegraph.mkf', 'c:\\marmalade\\7.5\\modules\\iw2d\\iw2d.mkf', 'c:\\marmalade\\7.5\\modules\\iwgx\\iwgx.mkf', 'c:\\marmalade\\7.5\\modules\\iwgl\\iwgl.mkf', 'c:\\marmalade\\7.5\\modules\\iwgeom\\iwgeom.mkf', 'c:\\marmalade\\7.5\\modules\\iwresmanager\\iwresmanager.mkf', 'c:\\marmalade\\7.5\\extensions\\pvrtextool\\pvrtextool.mkf', 'c:\\marmalade\\7.5\\modules\\iwgxfont\\iwgxfont.mkf', 'c:\\marmalade\\7.5\\modules\\third_party\\tiniconv\\tiniconv.mkf', 'c:\\marmalade\\7.5\\modules\\iwtween\\iwtween.mkf']

class DeployConfig(object):
    pass

######### ASSET GROUPS #############

assets = {}

assets['Default'] = [
    ('d:/School/cs115/AmazingMaze\data', '.', 0),
]

######### DEFAULT CONFIG #############

class DefaultConfig(DeployConfig):
    embed_icf = -1
    name = 'AmazingMaze'
    pub_sign_key = 0
    priv_sign_key = 0
    caption = 'AmazingMaze'
    long_caption = 'AmazingMaze'
    version = [0, 0, 1]
    config = ['d:/School/cs115/AmazingMaze/data/app.icf']
    data_dir = 'd:/School/cs115/AmazingMaze/data'
    mkb_dir = 'd:/School/cs115/AmazingMaze'
    iphone_link_lib = []
    osx_ext_dll = ['c:/marmalade/7.5/extensions/pvrtextool/lib/osx/libPVRTexTool.dylib']
    wp81_extra_pri = []
    ws8_ext_capabilities = []
    android_external_res = []
    win32_ext_dll = ['c:/marmalade/7.5/extensions/pvrtextool/lib/win32/PVRTexTool.dll']
    wp8_ext_capabilities = []
    ws8_extra_res = []
    ws81_ext_managed_dll = []
    iphone_link_libdir = []
    wp81_ext_capabilities = []
    android_extra_application_manifest = []
    ws8_ext_native_dll = []
    android_external_assets = []
    blackberry_extra_descriptor = []
    android_extra_manifest = []
    wp81_ext_sdk_ref = []
    iphone_link_libdirs = []
    wp81_ext_device_capabilities = []
    linux_ext_lib = []
    ws8_ext_managed_dll = []
    ws8_ext_sdk_manifest_part = []
    ws8_ext_device_capabilities = []
    ws81_extra_pri = []
    android_external_jars = []
    win8_winrt_extra_res = []
    wp81_ext_sdk_manifest_part = []
    android_supports_gl_texture = []
    wp81_extra_res = []
    wp81_ext_managed_dll = []
    iphone_extra_plist = []
    ws81_ext_sdk_manifest_part = []
    ws81_ext_device_capabilities = []
    ws8_ext_sdk_ref = []
    iphone_extra_string = []
    tizen_so = []
    wp8_ext_native_dll = []
    win8_phone_extra_res = []
    win8_store_extra_res = []
    iphone_link_opts = []
    ws81_ext_sdk_ref = []
    wp8_extra_res = []
    ws81_ext_native_dll = []
    ws8_extra_pri = []
    wp8_ext_managed_dll = []
    android_extra_packages = []
    android_so = []
    wp8_ext_sdk_ref = []
    osx_extra_res = []
    ws81_extra_res = []
    wp81_ext_native_dll = []
    ws81_ext_capabilities = []
    iphone_link_libs = []
    target = {
         'gcc_x86' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_gcc_x86/AmazingMaze.so',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_gcc_x86/AmazingMaze.so',
                 },
         'gcc_x86_tizen' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_gcc_x86_tizen/AmazingMaze.s86',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_gcc_x86_tizen/AmazingMaze.s86',
                 },
         'firefoxos' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_firefoxos/AmazingMaze.js',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_firefoxos/AmazingMaze.js',
                 },
         'mips_gcc' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_gcc_mips/AmazingMaze.so',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_gcc_mips/AmazingMaze.so',
                 },
         'arm_gcc' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_gcc_arm/AmazingMaze.s3e',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_gcc_arm/AmazingMaze.s3e',
                 },
         'mips' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_gcc_mips/AmazingMaze.so',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_gcc_mips/AmazingMaze.so',
                 },
         'aarch64_gcc' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_gcc_aarch64/AmazingMaze.s3e',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_gcc_aarch64/AmazingMaze.s3e',
                 },
         'gcc_x86_android' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_gcc_x86_android/AmazingMaze.so',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_gcc_x86_android/AmazingMaze.so',
                 },
         'arm' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_arm/AmazingMaze.s3e',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_arm/AmazingMaze.s3e',
                 },
         'x86' : {
                   'debug'   : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Debug_AmazingMaze_VC12_x86/AmazingMaze.s86',
                   'release' : r'd:/School/cs115/AmazingMaze/build_amazingmaze_vc12/Release_AmazingMaze_VC12_x86/AmazingMaze.s86',
                 },
        }
    arm_arch = ''
    assets_original = assets
    assets = assets['Default']

default = DefaultConfig()
